export const product = {
  id: 1,
  userId: 1,
  name: "Product 1",
  image: "https://example.com/product-1.jpg",
  description: "Description: This is product 1",
  brand: "Brand 1",
  category: "Category 1",
  price: 19.99,
  countInStock: 10,
  rating: 4.5,
  numReviews: 12,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const product2 = {
  id: 2,
  userId: 1,
  name: "Product 2",
  image: "https://example.com/product-1.jpg",
  description: "Description: This is product 1",
  brand: "Brand 1",
  category: "Category 1",
  price: 19.99,
  countInStock: 10,
  rating: 4.5,
  numReviews: 12,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const order = {
  id: 28,
  userId: 2,
  address: "大通り公園",
  city: "0600061",
  postalCode: "札幌",
  paymentMethod: "PayPal",
  paymentResultId: null,
  paymentResultStatus: null,
  paymentResultUpdateTime: null,
  paymentResultEmail: null,
  price: {
    itemsPrice: 89.99,
    taxPrice: 13.5,
    shippingPrice: 10,
    totalPrice: 113.49,
  },
  itemsPrice: 89.99,
  taxPrice: 13.5,
  shippingPrice: 10,
  totalPrice: 113.49,
  isPaid: false,
  paidAt: null,
  isDelivered: false,
  deliveredAt: null,
  createdAt: "2023-06-21T06:39:11.497Z",
  updatedAt: "2023-06-21T06:39:11.497Z",
  user: {
    id: 2,
    name: "john",
    email: "john@email.com",
    password: "$2a$10$eRfvYeJFQKph.3IVWhT5u.Ae7a74KF8DlWxvSKFrp3VqlVBb0k13m",
    isAdmin: false,
    createdAt: "2023-06-14T21:07:17.601Z",
    updatedAt: "2023-06-14T21:07:17.601Z",
  },
  orderProducts: [
    {
      orderId: 28,
      productId: 1,
      qty: 1,
      product: {
        id: 1,
        userId: 1,
        name: "Airpods Wireless Bluetooth Headphones",
        image: "/images/airpods.jpg",
        brand: "Apple",
        category: "Electronics",
        description:
          "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while wor",
        rating: 4.5,
        numReviews: 12,
        price: 89.99,
        countInStock: 10,
        createdAt: "2023-06-14T21:07:17.666Z",
        updatedAt: "2023-06-14T21:07:17.666Z",
      },
    },
  ],
};
